# Generated by Django 3.0.5 on 2020-05-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_date_posted'),
        ('products', '0003_auto_20200427_1251'),
    ]

    operations = [
    ]
